plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'dev.mixinmcp.decompile'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {

    // MixinSquared - MixinSquared's annotationProcessor MUST be registered BEFORE Mixin's one.
    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${mixin_squared_version}"))

    // compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // Neoforge also bundles fabric's mixin fork, so it's safe to use in common
    compileOnly(annotationProcessor("net.fabricmc:sponge-mixin:${fabric_mixin_version}"))

    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    // compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.3'
    // annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.3'



    // Fzzy Config
    implementation("me.fzzyhmstrs:fzzy_config:${fzzy_config}")

}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
